# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sk/tmp/maze

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sk/tmp/maze

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sk/tmp/maze/CMakeFiles /home/sk/tmp/maze/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sk/tmp/maze/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/build
.PHONY : game/fast

#=============================================================================
# Target rules for targets named editor

# Build rule for target.
editor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 editor
.PHONY : editor

# fast build rule for target.
editor/fast:
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/build
.PHONY : editor/fast

#=============================================================================
# Target rules for targets named maze

# Build rule for target.
maze: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 maze
.PHONY : maze

# fast build rule for target.
maze/fast:
	$(MAKE) -f CMakeFiles/maze.dir/build.make CMakeFiles/maze.dir/build
.PHONY : maze/fast

#=============================================================================
# Target rules for targets named menu

# Build rule for target.
menu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 menu
.PHONY : menu

# fast build rule for target.
menu/fast:
	$(MAKE) -f CMakeFiles/menu.dir/build.make CMakeFiles/menu.dir/build
.PHONY : menu/fast

src/editor.o: src/editor.cpp.o

.PHONY : src/editor.o

# target to build an object file
src/editor.cpp.o:
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/editor.cpp.o
.PHONY : src/editor.cpp.o

src/editor.i: src/editor.cpp.i

.PHONY : src/editor.i

# target to preprocess a source file
src/editor.cpp.i:
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/editor.cpp.i
.PHONY : src/editor.cpp.i

src/editor.s: src/editor.cpp.s

.PHONY : src/editor.s

# target to generate assembly for a file
src/editor.cpp.s:
	$(MAKE) -f CMakeFiles/editor.dir/build.make CMakeFiles/editor.dir/src/editor.cpp.s
.PHONY : src/editor.cpp.s

src/game.o: src/game.cpp.o

.PHONY : src/game.o

# target to build an object file
src/game.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game.cpp.o
.PHONY : src/game.cpp.o

src/game.i: src/game.cpp.i

.PHONY : src/game.i

# target to preprocess a source file
src/game.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game.cpp.i
.PHONY : src/game.cpp.i

src/game.s: src/game.cpp.s

.PHONY : src/game.s

# target to generate assembly for a file
src/game.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/game.cpp.s
.PHONY : src/game.cpp.s

src/maze.o: src/maze.cpp.o

.PHONY : src/maze.o

# target to build an object file
src/maze.cpp.o:
	$(MAKE) -f CMakeFiles/maze.dir/build.make CMakeFiles/maze.dir/src/maze.cpp.o
.PHONY : src/maze.cpp.o

src/maze.i: src/maze.cpp.i

.PHONY : src/maze.i

# target to preprocess a source file
src/maze.cpp.i:
	$(MAKE) -f CMakeFiles/maze.dir/build.make CMakeFiles/maze.dir/src/maze.cpp.i
.PHONY : src/maze.cpp.i

src/maze.s: src/maze.cpp.s

.PHONY : src/maze.s

# target to generate assembly for a file
src/maze.cpp.s:
	$(MAKE) -f CMakeFiles/maze.dir/build.make CMakeFiles/maze.dir/src/maze.cpp.s
.PHONY : src/maze.cpp.s

src/menu.o: src/menu.cpp.o

.PHONY : src/menu.o

# target to build an object file
src/menu.cpp.o:
	$(MAKE) -f CMakeFiles/menu.dir/build.make CMakeFiles/menu.dir/src/menu.cpp.o
.PHONY : src/menu.cpp.o

src/menu.i: src/menu.cpp.i

.PHONY : src/menu.i

# target to preprocess a source file
src/menu.cpp.i:
	$(MAKE) -f CMakeFiles/menu.dir/build.make CMakeFiles/menu.dir/src/menu.cpp.i
.PHONY : src/menu.cpp.i

src/menu.s: src/menu.cpp.s

.PHONY : src/menu.s

# target to generate assembly for a file
src/menu.cpp.s:
	$(MAKE) -f CMakeFiles/menu.dir/build.make CMakeFiles/menu.dir/src/menu.cpp.s
.PHONY : src/menu.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... game"
	@echo "... editor"
	@echo "... maze"
	@echo "... menu"
	@echo "... src/editor.o"
	@echo "... src/editor.i"
	@echo "... src/editor.s"
	@echo "... src/game.o"
	@echo "... src/game.i"
	@echo "... src/game.s"
	@echo "... src/maze.o"
	@echo "... src/maze.i"
	@echo "... src/maze.s"
	@echo "... src/menu.o"
	@echo "... src/menu.i"
	@echo "... src/menu.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

